//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18010
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UIAComWrapper {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringTable {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringTable() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UIAComWrapper.StringTable", typeof(StringTable).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to button.
        /// </summary>
        internal static string ControlTypeButton {
            get {
                return ResourceManager.GetString("ControlTypeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to calendar.
        /// </summary>
        internal static string ControlTypeCalendar {
            get {
                return ResourceManager.GetString("ControlTypeCalendar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to check box.
        /// </summary>
        internal static string ControlTypeCheckBox {
            get {
                return ResourceManager.GetString("ControlTypeCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to combo box.
        /// </summary>
        internal static string ControlTypeComboBox {
            get {
                return ResourceManager.GetString("ControlTypeComboBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to custom.
        /// </summary>
        internal static string ControlTypeCustom {
            get {
                return ResourceManager.GetString("ControlTypeCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to datagrid.
        /// </summary>
        internal static string ControlTypeDataGrid {
            get {
                return ResourceManager.GetString("ControlTypeDataGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dataitem.
        /// </summary>
        internal static string ControlTypeDataItem {
            get {
                return ResourceManager.GetString("ControlTypeDataItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to document.
        /// </summary>
        internal static string ControlTypeDocument {
            get {
                return ResourceManager.GetString("ControlTypeDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to edit.
        /// </summary>
        internal static string ControlTypeEdit {
            get {
                return ResourceManager.GetString("ControlTypeEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to group.
        /// </summary>
        internal static string ControlTypeGroup {
            get {
                return ResourceManager.GetString("ControlTypeGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to header.
        /// </summary>
        internal static string ControlTypeHeader {
            get {
                return ResourceManager.GetString("ControlTypeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to header item.
        /// </summary>
        internal static string ControlTypeHeaderItem {
            get {
                return ResourceManager.GetString("ControlTypeHeaderItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hyperlink.
        /// </summary>
        internal static string ControlTypeHyperlink {
            get {
                return ResourceManager.GetString("ControlTypeHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to image.
        /// </summary>
        internal static string ControlTypeImage {
            get {
                return ResourceManager.GetString("ControlTypeImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list item.
        /// </summary>
        internal static string ControlTypeListItem {
            get {
                return ResourceManager.GetString("ControlTypeListItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to list view.
        /// </summary>
        internal static string ControlTypeListView {
            get {
                return ResourceManager.GetString("ControlTypeListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menu.
        /// </summary>
        internal static string ControlTypeMenu {
            get {
                return ResourceManager.GetString("ControlTypeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menu bar.
        /// </summary>
        internal static string ControlTypeMenuBar {
            get {
                return ResourceManager.GetString("ControlTypeMenuBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to menu item.
        /// </summary>
        internal static string ControlTypeMenuItem {
            get {
                return ResourceManager.GetString("ControlTypeMenuItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pane.
        /// </summary>
        internal static string ControlTypePane {
            get {
                return ResourceManager.GetString("ControlTypePane", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to progress bar.
        /// </summary>
        internal static string ControlTypeProgressBar {
            get {
                return ResourceManager.GetString("ControlTypeProgressBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to radio button.
        /// </summary>
        internal static string ControlTypeRadioButton {
            get {
                return ResourceManager.GetString("ControlTypeRadioButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scroll bar.
        /// </summary>
        internal static string ControlTypeScrollBar {
            get {
                return ResourceManager.GetString("ControlTypeScrollBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to separator.
        /// </summary>
        internal static string ControlTypeSeparator {
            get {
                return ResourceManager.GetString("ControlTypeSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to slider.
        /// </summary>
        internal static string ControlTypeSlider {
            get {
                return ResourceManager.GetString("ControlTypeSlider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to spinner.
        /// </summary>
        internal static string ControlTypeSpinner {
            get {
                return ResourceManager.GetString("ControlTypeSpinner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to split button.
        /// </summary>
        internal static string ControlTypeSplitButton {
            get {
                return ResourceManager.GetString("ControlTypeSplitButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to status bar.
        /// </summary>
        internal static string ControlTypeStatusBar {
            get {
                return ResourceManager.GetString("ControlTypeStatusBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tab.
        /// </summary>
        internal static string ControlTypeTab {
            get {
                return ResourceManager.GetString("ControlTypeTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tab item.
        /// </summary>
        internal static string ControlTypeTabItem {
            get {
                return ResourceManager.GetString("ControlTypeTabItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to table.
        /// </summary>
        internal static string ControlTypeTable {
            get {
                return ResourceManager.GetString("ControlTypeTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to text.
        /// </summary>
        internal static string ControlTypeText {
            get {
                return ResourceManager.GetString("ControlTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to thumb.
        /// </summary>
        internal static string ControlTypeThumb {
            get {
                return ResourceManager.GetString("ControlTypeThumb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to title bar.
        /// </summary>
        internal static string ControlTypeTitleBar {
            get {
                return ResourceManager.GetString("ControlTypeTitleBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tool bar.
        /// </summary>
        internal static string ControlTypeToolBar {
            get {
                return ResourceManager.GetString("ControlTypeToolBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tool tip.
        /// </summary>
        internal static string ControlTypeToolTip {
            get {
                return ResourceManager.GetString("ControlTypeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tree view.
        /// </summary>
        internal static string ControlTypeTreeView {
            get {
                return ResourceManager.GetString("ControlTypeTreeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tree view item.
        /// </summary>
        internal static string ControlTypeTreeViewItem {
            get {
                return ResourceManager.GetString("ControlTypeTreeViewItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to window.
        /// </summary>
        internal static string ControlTypeWindow {
            get {
                return ResourceManager.GetString("ControlTypeWindow", resourceCulture);
            }
        }
    }
}
